version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$REPOSITORY_URI"
  build:
    commands:
      - docker build --platform linux/arm64 -t "$REPOSITORY_URI:prod" .
  post_build:
    commands:
      - docker push "$REPOSITORY_URI:prod"
